#!/usr/bin/ruby

#
#  tests_generator.rb
#  Filesystem Test Runner
#
#  Lustre Filesystem For macOS
#  Copyright (C) 2016 Cider Apps, LLC.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

require 'kconv'

def titleize(word)
    word.gsub(/\b[a-z]/) { $&.capitalize }
end


test_functions = {}

dir = ENV["PROJECT_DIR"] + "/Tests/Filesystem/*_test.c"

Dir.glob(dir).each do |f|
    section = f.split('/')[-1][0..-3].split('_test')[0]
    test_functions[section] = []
    
    IO.readlines(f).each_with_index do |l, i|
        ll = Kconv.toutf8(l)
        if ll =~ /^LUSTRE_TEST\((.*), (.*)\)/
            test_functions[section] << { name: $2, file: f, line: i+1 }
        end
    end
end

tests_directory = ENV["PROJECT_DIR"] + "/Tests/Filesystem Test Runner/Generated"
tests_file = tests_directory + "/LFSGeneratedTests.m"

Dir.mkdir(tests_directory) unless File.exists?(tests_directory)

file = File.open(tests_file, "w")

file << "//
//  LFSGeneratedTests.m
//  Filesystem Test Runner
//
//  Autogenerated File - Do Not Edit - Do Not Check In - See Test Runner Build Scheme
//
//  Lustre Filesystem For macOS
//  Copyright (C) 2016 Cider Apps, LLC.
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//


#import \"LFSTestCase.h\"

"

test_functions.each_pair do |section, tests|

file << "@interface LFSGenerated#{titleize(section)}Tests : LFSTestCase
@end

@implementation LFSGenerated#{titleize(section)}Tests

+ (void)initialize
{
    [LFSTestCase configureTestRunner:@\"#{ENV['UTILITY_VM']}\" snapshot:@\"#{ENV['UTILITY_SNAPSHOT']}\" hostname:@\"#{ENV['UTILITY_HOSTNAME']}\"];
}

"

tests.each do |test|
    file << "- (void)test#{titleize(test[:name])}
{
    // @link lustre_#{section}_#{test[:name]}_test
    [self runRemoteTest:@\"#{section}.#{test[:name]}\" runnerFile:@\"#{test[:file]}\" runnerLine:#{test[:line]}];
}

"
end

file << "@end

"

end

file.close
