#!/usr/bin/ruby

#
#  test_listings_generator.rb
#  Filesystem Test
#
#  Lustre Filesystem For macOS
#  Copyright (C) 2016 Cider Apps, LLC.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

require 'kconv'

test_functions = []

test_listings_directory = ENV["PROJECT_DIR"] + "/Tests/Filesystem/Generated"
test_listings_file = test_listings_directory + "/test_listings.h"

Dir.mkdir(test_listings_directory) unless File.exists?(test_listings_directory)

file = File.open(test_listings_file, "w")

dir = ENV["PROJECT_DIR"] + "/Tests/Filesystem/*_test.c"

Dir.glob(dir).each do |f|
    IO.readlines(f).each do |l|
        ll = Kconv.toutf8(l)
        if ll =~ /^LUSTRE_TEST\((.*), (.*)\)/
            test_functions << { section: $1, test: $2 }
        end
    end
end

file << "//
//  test_listings.h
//  Filesystem Test
//
//  Autogenerated File - Do Not Edit - Do Not Check In - See Filesystem Test Build Scheme
//
//  Lustre Filesystem For macOS
//  Copyright (C) 2016 Cider Apps, LLC.
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

#ifndef lustre_test_listings_h
#define lustre_test_listings_h

#include \"test.h\"

"

test_functions.each do |f|
    file << "void lustre_%s_%s_test LUSTRE_TEST_ARGS;
" % [f[:section], f[:test]]
end

file << "
const struct lustre_test_listing kLustreTestListings[] = {
"
    
test_functions.each do |f|
    file << "  { \"%s\", \"%s\", lustre_%s_%s_test },
" % [f[:section], f[:test], f[:section], f[:test],]
end

file << "};

const uint32_t kLustreTestListingsCount = #{test_functions.count};

#endif /* lustre_test_listings_h */
"

file.close
